version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: login-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: login_system
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
